### ISSUE TITLE
Enabling TF 1.4 with this DeepSpeech

### ISSUE THREAD

**Issue by wei-v-wang** [fordDeepDSP/deepSpeech#11]
Hi, 

I am trying to enabling TF 1.4 with this DeepSpeech. 
After some API changes, I have come to this error: 

Traceback (most recent call last):
  File "deepSpeech_train.py", line 441, in <module>
    main()
  File "deepSpeech_train.py", line 437, in main
    train()
  File "deepSpeech_train.py", line 378, in train
    loss_op, tower_grads, summaries = get_loss_grads(data, optimizer)
  File "deepSpeech_train.py", line 273, in get_loss_grads
    loss = tower_loss(scope, feats[i], labels[i], seq_lens[i])
  File "deepSpeech_train.py", line 156, in tower_loss
    loss_averages_op = loss_averages.apply(losses + [total_loss])
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/training/moving_averages.py", line 401, in apply
    colocate_with_primary=(var.op.type in ["Variable", "VariableV2"]))
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/training/slot_creator.py", line 151, in create_slot_with_initializer
    dtype)
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/training/slot_creator.py", line 67, in _create_slot_var
    validate_shape=validate_shape)
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/nfs/site/home/wangwei3/shared/tf/TF_GPU_PY3/tensorflow/python/ops/variable_scope.py", line 760, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable tower_1/ctc_loss/avg/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

Any suggestions? THanks!

**Comment by wei-v-wang** [comment]
Using r11 instead as suggested in previous issues.
