### ISSUE TITLE
ValueError: string_input_producer requires a non-null input tensor

### ISSUE THREAD

**Issue by jenweilee** [fordDeepDSP/deepSpeech#15]
I use the command in train.sh to give a first try of training.
But some errors happened as like the following messages:
Traceback (most recent call last):
  File "deepSpeech_train.py", line 441, in <module>
    main()
  File "deepSpeech_train.py", line 437, in main
    train()
  File "deepSpeech_train.py", line 375, in train
    data = fetch_data()
  File "deepSpeech_train.py", line 248, in fetch_data
    shuffle=ARGS.shuffle)
  File "/Users/jenweilee/git/deepSpeech-fordDeepDSP/code/deepSpeech.py", line 57, in inputs
    shuffle=shuffle)
  File "/Users/jenweilee/git/deepSpeech-fordDeepDSP/code/deepSpeech_input.py", line 95, in inputs
    filename_queue = tf.train.string_input_producer(filenames, shuffle=shuffle)
  File "/Users/jenweilee/anaconda3/envs/SpeechRecog/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 241, in string_input_producer
    raise ValueError(not_null_err)
ValueError: string_input_producer requires a non-null input tensor

do you guys have any idea?

**Comment by lscaria** [comment]
It looks like the model is having trouble finding the path to the preprocessed audio files. Could you print filenames in deepSpeech_input.py and double check what the output is. Otherwise you can use the --data_dir flag in your command line to direct it to where you have the preprocessed files.
