### ISSUE TITLE
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by supriyalk** [fordDeepDSP/deepSpeech#7]
When running the command: python3 deepSpeech_train.py --num_rnn_layers 3 --rnn_type 'bi-dir' --initial_lr 3e-4 --max_steps 3000
I get the following error: Traceback (most recent call last):
  File "/home/slkapur/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/home/slkapur/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/slkapur/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 614, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("bucket_by_sequence_length/bucket/dequeue_top:2", shape=(?, ?, 13), dtype=float32, device=/device:CPU:*)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deepSpeech_train.py", line 442, in <module>
    main()
  File "deepSpeech_train.py", line 438, in main
    train()
  File "deepSpeech_train.py", line 376, in train
    data = fetch_data()
  File "deepSpeech_train.py", line 251, in fetch_data
    split_feats = tf.split(0, ARGS.num_gpus, feats)
  File "/home/slkapur/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1214, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/slkapur/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3261, in _split
    num_split=num_split, name=name)
  File "/home/slkapur/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
(TF_011) slkapur@aal-gpu06:~/rnn_studies/deepSpeech/code$ TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
TypeError:: command not found

I have ensured that I am using Tensorflow 0.11, and think that this may be an issue in the code. Do you have any insight?

**Comment by mihail911** [comment]
One of the arguments fed into split() is expecting an integer whereas a float is provided, so the code is throwing an error. I don't remember which of the arguments for split() is supposed to the be split_dim (1st, 2nd, or 3rd), but it appears that parameter must be of type int. You should be able to find out this information in the TF docs online and that should help you hone in on where you are passing in the wrong expected type.

**Comment by supriyalk** [comment]
I actually figured out that I was referencing a newer version of tensorflow but I fixed that issue and now  I do not get that error. I still am getting an error though when I train the network. I am using the command from train.sh and running through the provided tutorial: 

I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 375.39.0
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:296] kernel version 375.39.0 does not match DSO version 375.66.0 -- cannot find working devices in this configuration
Traceback (most recent call last):
  File "deepSpeech_train.py", line 442, in <module>
    main()
  File "deepSpeech_train.py", line 438, in main
    train()
  File "deepSpeech_train.py", line 376, in train
    data = fetch_data()
  File "deepSpeech_train.py", line 251, in fetch_data
    split_feats = tf.split(0, ARGS.num_gpus, feats)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1038, in split
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2604, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 671, in apply_op
    (key, op_type_name, attr_value.i, attr_def.minimum))
ValueError: Attr 'num_split' of 'Split' Op passed 0 less than minimum 1.

Do you think this still could be an issue with the provided code and it's compatibility to tensorflow version 0.11?

**Comment by lscaria** [comment]
I think this is happening because deepSpeech is not seeing any active gpus. Specifically in line 251, split_feats = tf.split(0, ARGS.num_gpus, feats), it sees ARGS.num_gpus as 0 instead of the minimum 1. 

Try using the  --num_gpus flag in the train command to specify how many gpus you have
